export interface Sighting {
  id: string;
  date: string;
  time: string;
  location: string;
  country: string;
  locationType: string;
  imageUrl: string;
  credibility: number;
  strangeness: number;
  summary: string;
  duration: number;
  elevation: string;
  coords: string;
  latLon: [number, number]; // [latitude, longitude] in decimal degrees
  sourceId: string;
  hatchDesc: string;
  description: string;
  attributes: string[];
  reference: string;
  source: string;
  witnessType: string[];
  shape: string[];
  phenomena: string[];
}

export const mockSightings: Sighting[] = [
  {
    id: '1',
    date: '1952-07-19',
    time: '23:40',
    location: 'Washington, D.C.',
    country: 'États-Unis',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1648231150978-27af59c1d3ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXNoaW5ndG9uJTIwZGMlMjBjYXBpdG9sJTIwYnVpbGRpbmclMjBuaWdodHxlbnwxfHx8fDE3NjQ2ODEzMTl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 13,
    strangeness: 8,
    summary: 'Multiple radar contacts over Capitol. F-94 Starfires scrambled.',
    duration: 180,
    elevation: '5,000 ft',
    coords: '38.9072° N, 77.0369° W',
    latLon: [38.9072, -77.0369],
    sourceId: 'BB-1952-07-001',
    hatchDesc: 'Seven objects appeared on radar at Washington National Airport, tracked by multiple stations. Military jets scrambled but objects accelerated beyond aircraft capability. Witnessed by air traffic controllers and pilots.',
    description: `At approximately 11:40 PM, air traffic controller Edward Nugent noticed seven unidentified objects on his radar screen at Washington National Airport. The objects were not following any known flight paths and were moving at unusual speeds.\n\nCapital Airlines pilot Captain S.C. "Casey" Pierman reported seeing six bright lights overhead. He stated they were not ordinary aircraft lights. Multiple radar stations confirmed the targets.\n\nF-94 Starfighter jets were scrambled from New Castle Air Force Base. When the jets approached, the objects accelerated and disappeared from radar. Once the jets returned to base, the objects reappeared.\n\nThe incident lasted approximately three hours and involved multiple trained observers, radar operators, and military personnel. Similar events occurred the following weekend on July 26-27, 1952.`,
    attributes: ['Multiple Witnesses', 'Radar Confirmed', 'Military Response', 'High Speed', 'Intelligent Movement'],
    reference: 'Blue Book Case #1352',
    source: 'Project Blue Book Archives',
    witnessType: ['Militaires', 'Civils'],
    shape: ['Points lumineux'],
    phenomena: ['Enquêtes gouvernementales'],
  },
  {
    id: '2',
    date: '1976-09-19',
    time: '00:30',
    location: 'Tehran, Iran',
    country: 'Iran',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1701155640000-b3870364983a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWhyYW4lMjBpcmFuJTIwY2l0eSUyMHNreWxpbmV8ZW58MXx8fHwxNzY0NjgxMzE5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 14,
    strangeness: 9,
    summary: 'F-4 Phantom jets experienced equipment failure near luminous object.',
    duration: 90,
    elevation: '30,000 ft',
    coords: '35.6892° N, 51.3890° E',
    latLon: [35.6892, 51.3890],
    sourceId: 'DIA-1976-09-001',
    hatchDesc: 'Imperial Iranian Air Force F-4 Phantom II jets scrambled to intercept large luminous object. Multiple equipment failures occurred when approaching. Object demonstrated ability to launch smaller objects and disable weapons systems.',
    description: `At 12:30 AM, residents of Tehran reported seeing a large bright object in the sky. The Imperial Iranian Air Force scrambled an F-4 Phantom II to investigate.\n\nAs the first F-4 approached within 25 nautical miles, all instrumentation and communications were lost. The pilot broke off the intercept and headed back. Equipment returned to normal function.\n\nA second F-4 was launched. The pilot achieved radar lock at 27 nautical miles. The object's size on radar was comparable to a Boeing 707 tanker. As the pilot prepared to fire, all weapons control was lost, and communications failed.\n\nA smaller object detached from the primary object and headed straight for the F-4. The pilot attempted evasive maneuvers. The smaller object returned to the primary object which then departed at high speed.`,
    attributes: ['Military Encounter', 'Equipment Failure', 'Multiple Aircraft', 'Radar Lock', 'EM Effects'],
    reference: 'DIA Evaluation',
    source: 'Defense Intelligence Agency',
    witnessType: ['Militaires'],
    shape: ['Sphère'],
    phenomena: ['Effets sur humains', 'Enquêtes gouvernementales'],
  },
  {
    id: '3',
    date: '1980-12-27',
    time: '03:00',
    location: 'Rendlesham Forest, UK',
    country: 'Royaume-Uni',
    locationType: 'Forêt',
    imageUrl: 'https://images.unsplash.com/photo-1705711612617-3c6c335ae2ee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbmdsaXNoJTIwZm9yZXN0JTIwbmlnaHQlMjBteXN0ZXJ5fGVufDF8fHx8MTc2NDY4MTMyMHww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 12,
    strangeness: 9,
    summary: 'USAF personnel encountered triangular craft with landing traces.',
    duration: 120,
    elevation: 'Ground Level',
    coords: '52.0944° N, 1.4500° E',
    latLon: [52.0944, 1.4500],
    sourceId: 'MOD-1980-12-002',
    hatchDesc: 'United States Air Force security personnel at RAF Woodbridge witnessed triangular craft in forest. Physical trace evidence included landing impressions, broken branches, and elevated radiation readings at the landing site.',
    description: `In the early morning hours, USAF security patrol near the East Gate of RAF Woodbridge observed lights descending into Rendlesham Forest. Thinking an aircraft had crashed, they requested permission to investigate.\n\nThree patrolmen, including Staff Sergeant Jim Penniston, moved through the forest on foot. They encountered a triangular metallic craft approximately 9 feet long and 6.5 feet high. The surface was smooth with no visible seams or rivets.\n\nPenniston observed strange symbols on the craft's surface and touched it, noting it was warm. After approximately 45 minutes of observation, the craft lifted off and departed at impossible speed.\n\nThe next day, three depression marks were found in the ground forming a triangular pattern. Broken branches were found at about 10 feet height. Radiation readings at the landing site were significantly elevated.`,
    attributes: ['Physical Traces', 'Multiple Witnesses', 'Military Personnel', 'Radiation', 'Close Encounter'],
    reference: 'Halt Memorandum',
    source: 'UK Ministry of Defence',
    witnessType: ['Militaires'],
    shape: ['Triangle', 'Delta'],
    phenomena: ['Atterrissage', 'Traces physiques (RDA)', 'Faisceaux lumineux'],
  },
  {
    id: '4',
    date: '1964-04-24',
    time: '17:45',
    location: 'Socorro, New Mexico',
    country: 'États-Unis',
    locationType: 'Désert',
    imageUrl: 'https://images.unsplash.com/photo-1675819382159-a0e822ad668f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuZXclMjBtZXhpY28lMjBkZXNlcnQlMjBsYW5kc2NhcGV8ZW58MXx8fHwxNzY0NjgxMzIwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 11,
    strangeness: 8,
    summary: 'Police officer witnessed egg-shaped craft and humanoid figures.',
    duration: 15,
    elevation: 'Ground Level',
    coords: '34.0584° N, 106.8914° W',
    sourceId: 'BB-1964-04-003',
    hatchDesc: 'Veteran police officer Lonnie Zamora observed egg-shaped craft on the ground with two figures in white coveralls nearby. Physical evidence included landing marks, burnt vegetation, and fused sand.',
    description: `Officer Lonnie Zamora was in pursuit of a speeding vehicle when he heard a roar and saw flame in the sky. Thinking a dynamite shack had exploded, he broke off pursuit to investigate.\n\nApproaching the area, Zamora observed a shiny object in a gully about 150-200 yards away. As he drove closer, he saw it was egg-shaped, smooth, and white with red markings.\n\nTwo small figures in what appeared to be white coveralls were visible near the object. When they noticed Zamora, they seemed startled. The officer heard a loud roar and saw blue flame beneath the object as it lifted off.\n\nInvestigation of the landing site revealed four pad marks in the ground, each about 4 inches deep. Vegetation was burnt in a circular pattern. Sand particles showed evidence of intense heat exposure.`,
    attributes: ['Humanoid Entities', 'Physical Traces', 'Law Enforcement', 'Landing Marks', 'Burnt Vegetation'],
    reference: 'Project Blue Book Case #5742',
    source: 'Project Blue Book Archives',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Sphère'],
    phenomena: ['Atterrissage', 'Traces physiques (VEG)', 'Entité seule', 'Sons'],
  },
  {
    id: '5',
    date: '2004-11-14',
    time: '14:00',
    location: 'Pacific Ocean, USS Nimitz',
    country: 'États-Unis',
    locationType: 'Mer/Océan',
    imageUrl: 'https://images.unsplash.com/photo-1551739280-5f71dab3fe64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWNpZmljJTIwb2NlYW4lMjBhZXJpYWwlMjB2aWV3fGVufDF8fHx8MTc2NDY4MTMyMHww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 15,
    strangeness: 10,
    summary: 'Navy F/A-18 pilots encountered "Tic Tac" shaped craft with impossible flight characteristics.',
    duration: 10,
    elevation: '20,000 ft',
    coords: '31.0° N, 118.0° W',
    sourceId: 'USN-2004-11-014',
    hatchDesc: 'USS Princeton tracked anomalous aerial vehicles for two weeks. F/A-18 Super Hornets vectored to intercept. Pilots encountered white "Tic Tac" shaped object demonstrating physics-defying maneuvers with no visible means of propulsion.',
    description: `The USS Princeton had been tracking anomalous aircraft intermittently for two weeks. On November 14, F/A-18 Super Hornets from the USS Nimitz were directed to intercept.\n\nCommander David Fravor and Lieutenant Commander Jim Slaight observed a white object approximately 40 feet long shaped like a "Tic Tac" with no wings, exhaust, or visible propulsion. The object was hovering above an area of roiling water.\n\nWhen Fravor descended to investigate, the object mirrored his movements, then rapidly accelerated and disappeared. Radar operators confirmed the object reappeared at their CAP point—60 miles away—in less than a minute.\n\nA second flight captured infrared video of a similar object. The Navy later confirmed the footage as authentic and classified the objects as "unidentified aerial phenomena." The incident involved multiple trained observers, radar systems, and infrared tracking.`,
    attributes: ['Navy Encounter', 'Video Evidence', 'Radar Confirmed', 'Transmedium', 'Instantaneous Acceleration'],
    reference: 'USS Nimitz Strike Group',
    source: 'U.S. Navy / Pentagon',
    witnessType: ['Militaires', 'En mer'],
    shape: ['Cigare'],
    phenomena: ['Submersible', 'Enquêtes gouvernementales'],
  },
  {
    id: '6',
    date: '1994-09-16',
    time: '20:00',
    location: 'Ruwa, Zimbabwe',
    country: 'Zimbabwe',
    locationType: 'École',
    imageUrl: 'https://images.unsplash.com/photo-1553777907-f5dbbbb44d7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZnJpY2FuJTIwc2Nob29sJTIwcGxheWdyb3VuZHxlbnwxfHx8fDE3NjQ2ODEzMjF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 9,
    summary: '62 schoolchildren witness silver craft and beings near playground.',
    duration: 20,
    elevation: 'Ground Level',
    coords: '17.8892° S, 31.2447° E',
    sourceId: 'ARZ-1994-09-016',
    hatchDesc: 'Mass sighting by 62 children aged 6-12 at Ariel School. Silver disc-shaped craft landed near school grounds. Two beings in black suits observed. Children independently drew similar craft and beings.',
    description: `During morning recess at Ariel School, 62 children between ages 6 and 12 witnessed a silver disc-shaped craft land in a field near their playground. Teachers were inside having a meeting.\n\nThe children reported seeing one large craft and several smaller objects. Two beings described as having large black eyes and wearing tight black suits were observed near or on the craft.\n\nAccording to multiple witnesses, one being made eye contact with some children and communicated telepathically about environmental destruction and technology dangers.\n\nDr. John Mack, Harvard psychiatry professor, interviewed the children independently. Their stories remained consistent, and their drawings showed remarkable similarities despite no collaboration.`,
    attributes: ['Mass Sighting', 'Child Witnesses', 'Telepathic Communication', 'Multiple Beings', 'Consistent Testimony'],
    reference: 'Mack Investigation Report',
    source: 'Dr. John Mack / Ariel School',
    witnessType: ['Civils'],
    shape: ['Soucoupe'],
    phenomena: ['Atterrissage', 'Entité seule', 'Effets sur humains'],
  },
  {
    id: '7',
    date: '1947-07-08',
    time: '14:30',
    location: 'Roswell, New Mexico',
    country: 'États-Unis',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1655582768187-a8d0042b007d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNlcnQlMjByYW5jaCUyMGFiYW5kb25lZHxlbnwxfHx8fDE3NjQ2ODEzMjF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 9,
    strangeness: 10,
    summary: 'Rancher discovers debris field with unusual metallic materials.',
    duration: 0,
    elevation: 'Ground Level',
    coords: '33.3872° N, 104.5281° W',
    sourceId: 'ROS-1947-07-008',
    hatchDesc: 'Debris field discovered by rancher Mac Brazel. Material described as lightweight metallic substance that could not be cut, burned, or dented. Military recovery operation conducted.',
    description: `Rancher Mac Brazel discovered unusual debris scattered across a large field on the Foster Ranch. The material was described as lightweight, metallic, and resembling foil but impossibly strong.\n\nWhen attempts to cut, burn, or dent the material failed, Brazel reported the find to Sheriff George Wilcox, who contacted Roswell Army Air Field.\n\nMajor Jesse Marcel led the recovery team. He later stated the material was "nothing made on this earth." The military initially issued a press release stating they had recovered a "flying disc."\n\nWithin hours, the story changed to a weather balloon explanation. Witnesses reported seeing unusual symbols on some debris pieces. The site was cordoned off and debris was transported to multiple military facilities.`,
    attributes: ['Physical Evidence', 'Military Recovery', 'Debris Field', 'Unusual Materials', 'Official Investigation'],
    reference: 'Roswell Report',
    source: 'U.S. Army Air Force',
    witnessType: ['Civils', 'Militaires'],
    shape: ['Soucoupe'],
    phenomena: ['Traces physiques (TRC)', 'Enquêtes gouvernementales'],
  },
  {
    id: '8',
    date: '1989-11-29',
    time: '19:00',
    location: 'Eupen, Belgium',
    country: 'Belgique',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1724607409440-f3e730063ce9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWxnaXVtJTIwY2l0eSUyMG5pZ2h0JTIwbGlnaHRzfGVufDF8fHx8MTc2NDY4MTMyMnww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 13,
    strangeness: 9,
    summary: 'Massive triangular craft with bright lights observed by police.',
    duration: 120,
    elevation: '500 ft',
    coords: '50.6278° N, 6.0369° E',
    sourceId: 'BEL-1989-11-029',
    hatchDesc: 'Two police officers pursued large triangular craft with powerful searchlights. Object was silent, moved slowly, and tracked by ground radar. Part of Belgian UFO wave involving thousands of witnesses.',
    description: `Police officers Heinrich Nicoll and Hubert von Montigny observed a large triangular craft with brilliant lights at each corner and a red pulsating light in the center.\n\nThe object was completely silent despite its enormous size (estimated wingspan 120 feet). It moved very slowly, approximately 30 mph, at low altitude.\n\nThe officers followed in their vehicle for over 75 minutes, observing the craft make sharp turns and hover. Ground radar confirmed the object's presence and tracked its movements.\n\nThis sighting was part of the Belgian UFO wave that lasted from 1989-1990, involving over 13,500 reports and witnessed by military personnel, police, and civilians across Belgium.`,
    attributes: ['Triangle', 'Police Witnesses', 'Radar Confirmed', 'Silent', 'Low Altitude'],
    reference: 'SOBEPS Report',
    source: 'Belgian Society for Space Phenomena Studies',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Triangle', 'Delta'],
    phenomena: ['Faisceaux lumineux', 'Enquêtes gouvernementales'],
  },
  {
    id: '9',
    date: '1957-11-02',
    time: '23:00',
    location: 'Levelland, Texas',
    country: 'États-Unis',
    locationType: 'Autoroute',
    imageUrl: 'https://images.unsplash.com/photo-1729879679733-8ca2ac28fcc3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZXhhcyUyMGhpZ2h3YXklMjBuaWdodCUyMHJvYWR8ZW58MXx8fHwxNzY0NjgxMzIyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 11,
    strangeness: 8,
    summary: 'Multiple vehicles experienced engine failure near egg-shaped object.',
    duration: 180,
    elevation: 'Ground Level',
    coords: '33.5873° N, 102.3782° W',
    sourceId: 'BB-1957-11-002',
    hatchDesc: 'Over a 3-hour period, 15+ independent witnesses reported vehicle electrical failures when approaching bright egg-shaped object on or near Highway 116. Engines restarted after object departed.',
    description: `Between 11 PM on November 2 and 2 AM on November 3, more than 15 independent witnesses reported nearly identical experiences along a 10-mile stretch of Highway 116.\n\nWitnesses described a bright egg or torpedo-shaped object, approximately 200 feet long, resting on or hovering just above the road. As vehicles approached, engines died and headlights went out.\n\nPedro Saucedo and Joe Salaz were the first to report. Their truck engine died as they approached a glowing object. When the object departed with a roar, the engine restarted normally.\n\nSimilar reports followed from truck drivers, a fire marshal, and other motorists. Project Blue Book initially attributed the incidents to ball lightning, despite the lack of storm activity and the electromagnetic effects.`,
    attributes: ['EM Effects', 'Vehicle Interference', 'Multiple Witnesses', 'Independent Reports', 'Engine Failure'],
    reference: 'Project Blue Book Case #5284',
    source: 'Project Blue Book Archives',
    witnessType: ['Civils'],
    shape: ['Cigare'],
    phenomena: ['Effets sur véhicules', 'Sons'],
  },
  {
    id: '10',
    date: '1967-05-20',
    time: '09:00',
    location: 'Falcon Lake, Manitoba',
    country: 'Canada',
    locationType: 'Forêt',
    imageUrl: 'https://images.unsplash.com/photo-1644615750278-d27c53d59eda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW5hZGlhbiUyMGZvcmVzdCUyMGxha2UlMjB3aWxkZXJuZXNzfGVufDF8fHx8MTc2NDY4MTMyMnww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 9,
    summary: 'Amateur geologist burned by exhaust from disc-shaped craft.',
    duration: 30,
    elevation: 'Ground Level',
    coords: '49.7142° N, 95.1978° W',
    sourceId: 'CAN-1967-05-020',
    hatchDesc: 'Stefan Michalak approached landed disc and was burned by hot gas emission. Physical evidence included burn marks on body in grid pattern, radioactive contamination at landing site, and melted silver.',
    description: `Amateur geologist Stefan Michalak was prospecting when he observed two cigar-shaped objects descending. One departed; the other landed about 160 feet away.\n\nThe object transformed into a disc shape, about 40 feet in diameter, with a dome on top. It was intensely bright and appeared to be made of stainless steel. Michalak heard mechanical sounds and voices from inside.\n\nHe approached and touched the craft, melting his glove. A grid-like panel opened and expelled hot gas, setting his shirt on fire and burning his chest and abdomen in a distinct grid pattern.\n\nMedical examination revealed first-degree burns in a grid pattern of circles. The landing site showed radioactive contamination and a circular burn mark. Michalak experienced radiation sickness symptoms for weeks.`,
    attributes: ['Physical Injury', 'Radiation Burns', 'Landing Site', 'Physical Traces', 'Medical Documentation'],
    reference: 'Project Bluebook - Canadian Report',
    source: 'Royal Canadian Mounted Police',
    witnessType: ['Civils'],
    shape: ['Soucoupe', 'Cigare'],
    phenomena: ['Atterrissage', 'Traces physiques (RDA)', 'Effets sur humains', 'Sons'],
  },
  {
    id: '11',
    date: '1986-11-17',
    time: '17:10',
    location: 'Alaska Airlines Flight 1628',
    country: 'États-Unis',
    locationType: 'Aéroport',
    imageUrl: 'https://images.unsplash.com/photo-1701143920557-1aa32dfec363?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbGFza2ElMjBtb3VudGFpbnMlMjBhZXJpYWwlMjB2aWV3fGVufDF8fHx8MTc2NDY4MTMyM3ww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 12,
    strangeness: 9,
    summary: 'Japanese cargo flight pursued by gigantic walnut-shaped craft.',
    duration: 50,
    elevation: '35,000 ft',
    coords: '64.2008° N, 149.4937° W',
    sourceId: 'FAA-1986-11-017',
    hatchDesc: 'Japan Airlines cargo flight tracked by two small objects and one enormous craft described as "mothership." Radar confirmed. FAA investigated. Captain Terauchi reported craft was twice the size of aircraft carrier.',
    description: `Captain Kenju Terauchi was piloting JAL cargo flight 1628 from Paris to Tokyo over Alaska when two small objects with square, glowing nozzle-like features appeared.\n\nThe objects moved in formation, matching the Boeing 747's speed and altitude for several minutes. The cockpit became so warm from their light that the crew felt heat on their faces.\n\nSuddenly, an enormous craft appeared - "twice the size of an aircraft carrier," according to Terauchi. It was walnut-shaped and paced the 747 for over 30 minutes.\n\nFAA radar at Anchorage confirmed a large target near the 747. Military radar also tracked the object. The FAA investigated for over three months before stating it could not identify the object.`,
    attributes: ['Airline Encounter', 'Radar Confirmed', 'Multiple Objects', 'Gigantic Scale', 'FAA Investigation'],
    reference: 'FAA Incident Report',
    source: 'Federal Aviation Administration',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Sphère', 'Sonde'],
    phenomena: ['Effets sur humains', 'Enquêtes gouvernementales'],
  },
  {
    id: '12',
    date: '1561-04-04',
    time: '07:00',
    location: 'Nuremberg, Germany',
    country: 'Allemagne',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1560335213-9300d1fd6d4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoaXN0b3JpYyUyMGdlcm1hbiUyMGNpdHklMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzY0NjgxMzIzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 7,
    strangeness: 10,
    summary: 'Celestial phenomenon involving hundreds of objects witnessed by entire city.',
    duration: 60,
    elevation: 'High Altitude',
    coords: '49.4521° N, 11.0767° E',
    sourceId: 'HIS-1561-04-004',
    hatchDesc: 'Mass sighting documented in broadsheet by Hans Glaser. Hundreds of objects described as spheres, cylinders, and crosses engaged in apparent aerial battle. Event witnessed by entire city population.',
    description: `At sunrise, residents of Nuremberg witnessed an extraordinary celestial event. According to the broadsheet by Hans Glaser, hundreds of objects appeared in the sky.\n\nWitnesses described spheres "approximately three in the length, from time to time, four in a square, much remained insulated, and between these spheres, one saw a number of crosses with the color of blood."\n\nLarge cylindrical objects were also reported, from which emerged spheres and other shapes. The objects appeared to engage in some form of aerial combat or coordinated maneuver.\n\nAfter approximately one hour, the objects descended and appeared to crash outside the city in a large amount of smoke. A black spear-like object was also reported. The event was witnessed by the entire population.`,
    attributes: ['Historical', 'Mass Sighting', 'Multiple Objects', 'Documented', 'Entire City'],
    reference: 'Nuremberg Broadsheet 1561',
    source: 'Historical Archives',
    witnessType: ['Civils'],
    shape: ['Sphère', 'Cylindre', 'Cigare'],
    phenomena: ['Signaux'],
  },
  {
    id: '13',
    date: '1994-03-08',
    time: '20:30',
    location: 'Holland, Michigan',
    country: 'États-Unis',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1696346315399-5c19755d2eed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYWtlJTIwbWljaGlnYW4lMjBzaG9yZWxpbmV8ZW58MXx8fHwxNzY0NjgxMzIzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 11,
    strangeness: 8,
    summary: '300+ witnesses report lights and objects; tracked by National Weather Service.',
    duration: 90,
    elevation: 'Various',
    coords: '42.7875° N, 86.1089° W',
    sourceId: 'NWS-1994-03-008',
    hatchDesc: 'Mass sighting involving over 300 witnesses including police officers. National Weather Service radar operator tracked objects. Lights and cylindrical objects reported performing unusual maneuvers.',
    description: `Over 300 witnesses, including multiple police officers, reported unusual lights and objects in the sky above Lake Michigan and Holland, Michigan.\n\nOfficers reported cylindrical objects with red, white, and green lights performing movements impossible for conventional aircraft. Objects appeared to descend into Lake Michigan.\n\nJack Bushong, National Weather Service radar operator, tracked the objects on weather radar for several hours. He confirmed multiple solid targets moving at various speeds and altitudes.\n\nPolice dispatch logged dozens of calls. Officers gave chase in patrol vehicles but objects outpaced them. Some witnesses reported objects splitting apart and reforming. The event lasted approximately 90 minutes with consistent reports.`,
    attributes: ['Mass Sighting', 'Radar Confirmed', 'Police Witnesses', 'Multiple Objects', 'NWS Tracking'],
    reference: 'NWS Radar Report',
    source: 'National Weather Service / Police Reports',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Cylindre', 'Points lumineux'],
    phenomena: ['Submersible'],
  },
  {
    id: '14',
    date: '1973-10-11',
    time: '21:00',
    location: 'Pascagoula, Mississippi',
    country: 'États-Unis',
    locationType: 'Côte',
    imageUrl: 'https://images.unsplash.com/photo-1601071948544-1391f8b74686?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaXNzaXNzaXBwaSUyMHJpdmVyJTIwY29hc3QlMjBuaWdodHxlbnwxfHx8fDE3NjQ2ODEzMjR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 9,
    strangeness: 10,
    summary: 'Two fishermen report abduction by robotic entities.',
    duration: 20,
    elevation: 'Ground Level',
    coords: '30.3658° N, 88.5561° W',
    sourceId: 'PAS-1973-10-011',
    hatchDesc: 'Charles Hickson and Calvin Parker abducted while fishing. Described floating into craft and examination by robotic entities with crab-like claws. Polygraph tests showed no deception.',
    description: `Charles Hickson, 42, and Calvin Parker, 19, were fishing from a pier when they heard a whirring sound and saw a blue light.\n\nAn oval-shaped object approximately 40 feet across and 10 feet high appeared. Three entities floated out - described as robotic, about 5 feet tall, with gray wrinkled skin, crab-like pincers, and no discernible eyes.\n\nBoth men reported being paralyzed and floated into the craft. Inside, they were subjected to some form of examination by a mechanical eye-like device. The entities did not communicate.\n\nAfter approximately 20 minutes, the men were returned to the pier. They were so frightened they considered not reporting it. Both passed polygraph tests. Secret recordings of their private conversation showed genuine distress.`,
    attributes: ['Abduction', 'Multiple Witnesses', 'Robotic Entities', 'Polygraph Verified', 'Physical Examination'],
    reference: 'Pascagoula Abduction Report',
    source: 'Jackson County Sheriff / Air Force',
    witnessType: ['Civils'],
    shape: ['Sphère'],
    phenomena: ['Effets sur humains', 'Entité seule'],
  },
  {
    id: '15',
    date: '1976-01-06',
    time: '19:20',
    location: 'Stanford, Kentucky',
    country: 'États-Unis',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1744236404768-8560dd4ef6af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxrZW50dWNreSUyMHJ1cmFsJTIwY291bnRyeXNpZGUlMjByb2FkfGVufDF8fHx8MTc2NDY4MTMyNHww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 9,
    summary: 'Three women abducted; physical evidence and missing time documented.',
    duration: 90,
    elevation: 'Ground Level',
    coords: '37.5312° N, 84.6621° W',
    sourceId: 'KEN-1976-01-006',
    hatchDesc: 'Mona Stafford, Louise Smith, and Elaine Thomas experienced missing time, physiological effects, and witnessed large disc-shaped object. Documented burn marks on bodies and vehicle. Regression revealed abduction memories.',
    description: `Three women were driving home when they observed a large disc-shaped object with a dome on top. The object was approximately 300 feet in diameter with brilliant red lights.\n\nThe women experienced a period of missing time. What should have been a 30-minute drive took over 2 hours. All three had severe physiological effects including burns on their bodies, eye irritation, and memory loss.\n\nUnder hypnotic regression conducted separately, all three described being taken aboard the craft and subjected to medical examinations. Their accounts were remarkably consistent despite being conducted independently.\n\nPhysical evidence included burn marks on their necks and arms in unusual patterns, damage to the car's hood, and time loss verified by multiple clocks and witnesses who expected them earlier.`,
    attributes: ['Abduction', 'Multiple Witnesses', 'Missing Time', 'Physical Burns', 'Hypnotic Regression'],
    reference: 'Stanford Abduction Case',
    source: 'Dr. Leo Sprinkle Investigation',
    witnessType: ['Civils'],
    shape: ['Soucoupe'],
    phenomena: ['Effets sur humains', 'Effets sur bâtiments'],
  },
  {
    id: '16',
    date: '1942-02-25',
    time: '02:25',
    location: 'Los Angeles, California',
    country: 'États-Unis',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1636734752838-1cb26a0a8031?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsb3MlMjBhbmdlbGVzJTIwY2l0eXNjYXBlJTIwbmlnaHQlMjB2aW50YWdlfGVufDF8fHx8MTc2NDY4MTMyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 11,
    strangeness: 8,
    summary: 'Military fires 1,400 rounds at unidentified object over city.',
    duration: 60,
    elevation: '8,000 ft',
    coords: '34.0522° N, 118.2437° W',
    sourceId: 'MIL-1942-02-025',
    hatchDesc: 'Battle of Los Angeles. Anti-aircraft batteries fired over 1,400 rounds at unidentified object(s) in sky. Despite direct hits reported, object(s) not brought down. Event witnessed by thousands across city.',
    description: `Just after 2 AM, air raid sirens sounded across Los Angeles. Anti-aircraft batteries opened fire on unidentified object(s) in the sky, with over 1,400 rounds of ammunition expended.\n\nThousands of witnesses observed searchlights converging on a large object in the sky. Despite numerous apparent direct hits, the object did not fall or appear damaged. Some witnesses reported seeing multiple smaller objects.\n\nThe barrage lasted for over an hour, with shells exploding throughout the sky creating an impressive display visible across the entire city. Falling shrapnel caused property damage and casualties on the ground.\n\nThe military initially stated enemy aircraft had been over the city. The next day, officials suggested false alarm and "war nerves." No aircraft wreckage was ever recovered. The incident remains unexplained.`,
    attributes: ['Military Action', 'Mass Sighting', 'Anti-Aircraft Fire', 'No Damage to Object', 'Official Confusion'],
    reference: 'Battle of Los Angeles',
    source: 'U.S. Army / Historical Records',
    witnessType: ['Militaires', 'Civils'],
    shape: ['Sphère'],
    phenomena: ['Enquêtes gouvernementales'],
  },
  {
    id: '17',
    date: '1897-04-17',
    time: '22:00',
    location: 'Aurora, Texas',
    country: 'États-Unis',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1749523910094-71e3e5a293e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZXhhcyUyMHNtYWxsJTIwdG93biUyMHJ1cmFsfGVufDF8fHx8MTc2NDY4MTMyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 6,
    strangeness: 10,
    summary: 'Airship crash with alleged non-human pilot; buried in town cemetery.',
    duration: 0,
    elevation: 'Ground Level',
    coords: '33.0537° N, 97.5164° W',
    sourceId: 'HIS-1897-04-017',
    hatchDesc: 'Historical account of airship crash into windmill. Debris recovered included unknown metal. Pilot described as "not of this world" and allegedly buried in Aurora cemetery. Part of 1897 airship wave.',
    description: `According to reports in the Dallas Morning News, an airship crashed into Judge Proctor's windmill and exploded. The crash was allegedly witnessed by the town.\n\nResidents reportedly found the badly disfigured pilot in the wreckage. T.J. Weems, a U.S. Signal Service officer, examined the body and stated the pilot was "not an inhabitant of this world."\n\nDebris from the craft was described as an unknown metal. Papers covered with hieroglyphic writing were allegedly found. The pilot was given a Christian burial in Aurora cemetery.\n\nThis incident was part of the Great Airship Wave of 1897 that saw thousands of sightings across the United States. While skepticism exists about the Aurora crash, it remains part of historical record and local legend.`,
    attributes: ['Historical', 'Crash/Retrieval', 'Non-Human Pilot', 'Metal Debris', 'Burial'],
    reference: 'Dallas Morning News 1897',
    source: 'Historical Newspaper Archives',
    witnessType: ['Civils'],
    shape: ['Cigare'],
    phenomena: ['Traces physiques (TRC)', 'Entité seule'],
  },
  {
    id: '18',
    date: '2006-11-07',
    time: '16:30',
    location: "O'Hare International Airport",
    country: 'États-Unis',
    locationType: 'Aéroport',
    imageUrl: 'https://images.unsplash.com/photo-1599961092534-746a7648fb98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGljYWdvJTIwYWlycG9ydCUyMHRlcm1pbmFsfGVufDF8fHx8MTc2NDY4MTMyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 12,
    strangeness: 8,
    summary: 'United Airlines employees witness disc hovering over gate C17.',
    duration: 5,
    elevation: '1,900 ft',
    coords: '41.9742° N, 87.9073° W',
    sourceId: 'FAA-2006-11-007',
    hatchDesc: 'Multiple United Airlines employees witnessed metallic disc hovering below cloud layer above gate C17. Object shot upward punching hole through clouds. FAA declined to investigate.',
    description: `At approximately 4:30 PM, multiple United Airlines employees and witnesses observed a dark gray metallic disc hovering below the cloud layer above gate C17.\n\nThe object was described as approximately 6-24 feet in diameter, solid, and clearly defined. It hovered for several minutes, rotating slowly. No sound was reported.\n\nSuddenly, the object shot straight upward at high velocity, punching a clear, defined circular hole through the cloud layer. The hole remained visible for several minutes.\n\nDozens of witnesses including pilots, mechanics, and airline management observed the event. Despite multiple witness reports, the FAA stated it was a "weather phenomenon" and declined to investigate. The Chicago Tribune obtained the story through Freedom of Information Act requests.`,
    attributes: ['Multiple Witnesses', 'Airport Sighting', 'Professional Observers', 'Physical Effect on Clouds', 'FAA Response'],
    reference: "O'Hare UFO Incident",
    source: 'FAA / Chicago Tribune Investigation',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Soucoupe'],
    phenomena: [],
  },
  {
    id: '19',
    date: '1976-08-13',
    time: '22:00',
    location: 'Allagash, Maine',
    country: 'États-Unis',
    locationType: 'Lac/Rivière',
    imageUrl: 'https://images.unsplash.com/photo-1598507690808-57594afea85f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWluZSUyMHdpbGRlcm5lc3MlMjBsYWtlJTIwY2FtcGluZ3xlbnwxfHx8fDE3NjQ2ODEzMjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 9,
    strangeness: 9,
    summary: 'Four men abducted while camping; corroborating memories under hypnosis.',
    duration: 180,
    elevation: 'Ground Level',
    coords: '47.0619° N, 69.0739° W',
    sourceId: 'ALL-1976-08-013',
    hatchDesc: 'Four men camping witnessed large glowing sphere. All experienced missing time and later recalled abduction under separate hypnotic regression sessions. Memories were remarkably consistent.',
    description: `Twin brothers Jack and Jim Weiner, along with Charlie Foltz and Chuck Rak, were on a camping trip when they observed a large bright sphere of light hovering over the lake.\n\nThe men made a large fire as a beacon and got in their canoe to investigate. As they approached, a bright beam of light engulfed them. Their next memory was standing on the shore with the fire reduced to embers - hours had passed.\n\nAll four men later experienced recurring nightmares and anxiety. Under separate hypnotic regression sessions conducted by different therapists, all four recalled being taken aboard a craft.\n\nThey described medical examinations by beings with large heads and dark eyes. The consistency of their independently recalled memories, despite being questioned separately by different investigators, is considered significant. All four passed polygraph examinations.`,
    attributes: ['Abduction', 'Multiple Witnesses', 'Missing Time', 'Hypnotic Regression', 'Consistent Memories'],
    reference: 'Allagash Abduction',
    source: 'Investigated by Raymond Fowler',
    witnessType: ['Civils'],
    shape: ['Sphère'],
    phenomena: ['Faisceaux lumineux', 'Effets sur humains'],
  },
  {
    id: '20',
    date: '1965-12-09',
    time: '17:47',
    location: 'Kecksburg, Pennsylvania',
    country: 'États-Unis',
    locationType: 'Forêt',
    imageUrl: 'https://images.unsplash.com/photo-1696965479108-41f160ee2cac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZW5uc3lsdmFuaWElMjBmb3Jlc3QlMjBkYXJrfGVufDF8fHx8MTc2NDY4MTMyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 9,
    summary: 'Acorn-shaped object crashes; military recovery operation follows.',
    duration: 0,
    elevation: 'Ground Level',
    coords: '40.1842° N, 79.4603° W',
    sourceId: 'MIL-1965-12-009',
    hatchDesc: 'Acorn-shaped object crashed in wooded area. Military cordoned off site and removed object on flatbed truck. Witnesses reported hieroglyphic-like symbols. Object tracked across multiple states and Canada.',
    description: `Thousands of witnesses across six U.S. states and Canada observed a fireball streaking across the sky. The object made controlled turns, ruling out meteor explanation.\n\nResidents near Kecksburg reported hearing a loud crash in the woods. Several witnesses, including local volunteer fire department members, reached the crash site before military arrival.\n\nWitnesses described an acorn-shaped object approximately 9-12 feet long, bronze-colored, with a band of hieroglyphic-like symbols around the base. The object was reportedly warm but not hot.\n\nMilitary personnel quickly arrived, cordoned off the area, and removed the object on a flatbed truck. Officials stated nothing was found. Documents later released through FOIA requests showed extensive military interest and activity contradicting the official story.`,
    attributes: ['Crash/Retrieval', 'Military Recovery', 'Multiple Witnesses', 'Hieroglyphic Symbols', 'Multi-State Tracking'],
    reference: 'Kecksburg Incident',
    source: 'NASA / U.S. Army',
    witnessType: ['Civils', 'Militaires'],
    shape: ['Sonde'],
    phenomena: ['Traces physiques (TRC)', 'Enquêtes gouvernementales'],
  },
  {
    id: '21',
    date: '1980-08-08',
    time: '01:00',
    location: 'Todmorden, UK',
    country: 'Royaume-Uni',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1638798169576-9fb774eee26a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1ayUyMGNvdW50cnlzaWRlJTIwZm9nZ3klMjByb2FkfGVufDF8fHx8MTc2NDY4MTMyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 9,
    strangeness: 9,
    summary: 'Police officer experiences missing time; discovered disoriented.',
    duration: 60,
    elevation: 'Ground Level',
    coords: '53.7126° N, 2.0986° W',
    sourceId: 'UK-1980-08-008',
    hatchDesc: 'Police Constable Alan Godfrey encountered diamond-shaped object on road. Experienced missing time and was found disoriented. Boot was split, unusual marks on foot. Under hypnosis, recalled examination aboard craft.',
    description: `Police Constable Alan Godfrey was on patrol searching for missing cattle when he encountered a large diamond-shaped object hovering over the road, rotating.\n\nThe object was approximately 20 feet in diameter, emitting bright light. Godfrey attempted to sketch it when he experienced a discontinuity. His next clear memory was driving down the road, further along than he should have been.\n\nHe discovered his boot was split, and there were unusual marks on his foot. Time was missing from his patrol - he could not account for approximately one hour.\n\nUnder hypnotic regression, Godfrey recalled being taken aboard the craft and examined by beings. His case is particularly credible as he was an active police officer with no prior interest in UFO phenomena. Several other officers witnessed unusual lights that same night.`,
    attributes: ['Police Witness', 'Missing Time', 'Physical Traces on Body', 'Hypnotic Regression', 'Credible Witness'],
    reference: 'Todmorden Police Report',
    source: 'West Yorkshire Police',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Delta'],
    phenomena: ['Effets sur humains'],
  },
  {
    id: '22',
    date: '1975-11-07',
    time: '18:15',
    location: 'Travis Walton, Arizona',
    country: 'États-Unis',
    locationType: 'Forêt',
    imageUrl: 'https://images.unsplash.com/photo-1762572805489-b3e9bc631d88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcml6b25hJTIwZm9yZXN0JTIwcGluZXN8ZW58MXx8fHwxNzY0NjgxMzI3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 10,
    summary: 'Logger missing for 5 days after beam of light; six co-workers witnesses.',
    duration: 7200,
    elevation: 'Ground Level',
    coords: '34.3875° N, 110.5443° W',
    sourceId: 'TRA-1975-11-007',
    hatchDesc: 'Travis Walton struck by beam of light from hovering disc. Missing for 5 days. Six co-workers witnessed event. All passed polygraph tests. Walton recovered with fragmented memories of time aboard craft.',
    description: `Seven loggers were driving home when they observed a large disc-shaped object hovering near the road. Travis Walton exited the truck to investigate more closely.\n\nA brilliant beam of light struck Walton, lifting him off the ground. Terrified, the other six men fled in the truck. They returned minutes later but found no trace of Walton or the craft.\n\nWalton was missing for 5 days. Extensive search operations found no trace. He reappeared disoriented on a highway, with fragmented memories of being aboard a craft with both gray beings and human-like entities.\n\nAll six witnesses passed polygraph examinations regarding what they saw. Walton also passed multiple polygraph tests. The case involved law enforcement investigation, media coverage, and remains one of the most documented abduction cases. The event was investigated extensively and later became the subject of the film "Fire in the Sky."`,
    attributes: ['Abduction', 'Missing 5 Days', 'Multiple Witnesses', 'Polygraph Verified', 'Beam of Light'],
    reference: 'Travis Walton Abduction',
    source: 'Navajo County Sheriff / Investigated by APRO',
    witnessType: ['Civils'],
    shape: ['Soucoupe'],
    phenomena: ['Faisceaux lumineux', 'Effets sur humains', 'Entité seule'],
  },
  {
    id: '23',
    date: '1952-09-12',
    time: '22:00',
    location: 'Flatwoods, West Virginia',
    country: 'États-Unis',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1635553140834-0e78ed6710bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZXN0JTIwdmlyZ2luaWElMjBydXJhbCUyMG1vdW50YWlufGVufDF8fHx8MTc2NDY4MTMyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 8,
    strangeness: 10,
    summary: 'Witnesses encounter tall entity with glowing eyes and hovering craft.',
    duration: 15,
    elevation: 'Ground Level',
    coords: '38.6673° N, 80.6498° W',
    sourceId: 'FLA-1952-09-012',
    hatchDesc: 'Multiple witnesses including children saw fiery object land on hill. Investigation found 10-12 foot tall entity with glowing orange-red eyes and metallic suit. Witnesses experienced nausea and vomiting.',
    description: `Three boys observed a bright object cross the sky and appear to land on a nearby hill. They recruited several others, including National Guardsman Gene Lemon, to investigate.\n\nThe group encountered a pungent mist that made them nauseous. They discovered a large pulsating object approximately 10 feet in diameter emitting a reddish light.\n\nSuddenly, they saw a towering figure, estimated 10-12 feet tall, with a blood-red face and glowing orange-red eyes. The entity was wearing what appeared to be a dark metallic suit with a pleated skirt.\n\nThe group fled in terror. Several witnesses, including children, vomited and experienced symptoms consistent with exposure to toxic substances. Law enforcement and reporters visited the site and reported unusual smells and evidence of something large having been present. Grass was flattened in a large circular pattern.`,
    attributes: ['Tall Entity', 'Multiple Witnesses', 'Physical Effects', 'Glowing Eyes', 'Landing Site'],
    reference: 'Flatwoods Monster',
    source: 'Braxton County Sheriff / News Reports',
    witnessType: ['Civils'],
    shape: ['Sphère'],
    phenomena: ['Atterrissage', 'Entité seule', 'Effets sur humains', 'Traces physiques (VEG)'],
  },
  {
    id: '24',
    date: '2010-09-08',
    time: '23:00',
    location: 'Xiaoshan Airport, China',
    country: 'Chine',
    locationType: 'Aéroport',
    imageUrl: 'https://images.unsplash.com/photo-1647668257295-1b26c7ac1ed9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGluZXNlJTIwYWlycG9ydCUyMG5pZ2h0JTIwbW9kZXJufGVufDF8fHx8MTc2NDY4MTMyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 11,
    strangeness: 8,
    summary: 'Airport shut down for hour; UFO photographed by multiple witnesses.',
    duration: 60,
    elevation: '3,000 ft',
    coords: '30.2294° N, 120.4344° E',
    sourceId: 'CHN-2010-09-008',
    hatchDesc: 'Hangzhou Xiaoshan International Airport completely shut down. UFO detected on radar and observed visually. Multiple photographs from different witnesses. Flights diverted. Official investigation launched.',
    description: `Hangzhou Xiaoshan International Airport was completely shut down when an unidentified flying object was detected on radar and observed by tower personnel.\n\nThe object appeared on radar and was visible to the naked eye, described as having a brilliant golden trail. Airport operations were suspended for approximately one hour while the object was present.\n\nEighteen flights were either diverted to nearby airports or delayed. Thousands of passengers were affected. Multiple witnesses photographed the object, with images showing a luminous object with a trail.\n\nChinese authorities launched an official investigation. While several theories were proposed (military test, private aircraft, natural phenomenon), no definitive explanation was provided. The incident received widespread Chinese media coverage and remains officially unexplained.`,
    attributes: ['Airport Closure', 'Radar Confirmed', 'Multiple Photographs', 'Flight Diversions', 'Official Investigation'],
    reference: 'Xiaoshan Airport Incident',
    source: 'Civil Aviation Administration of China',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Points lumineux'],
    phenomena: ['Signaux', 'Enquêtes gouvernementales'],
  },
  {
    id: '25',
    date: '1973-10-17',
    time: '23:00',
    location: 'Falkville, Alabama',
    country: 'États-Unis',
    locationType: 'Autoroute',
    imageUrl: 'https://images.unsplash.com/photo-1702394045860-361446d52b2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbGFiYW1hJTIwaGlnaHdheSUyMG5pZ2h0JTIwZW1wdHl8ZW58MXx8fHwxNzY0NjgxMzI4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 8,
    strangeness: 9,
    summary: 'Police chief photographs metallic humanoid entity on highway.',
    duration: 10,
    elevation: 'Ground Level',
    coords: '34.3690° N, 86.9086° W',
    sourceId: 'FAL-1973-10-017',
    hatchDesc: 'Police Chief Jeff Greenhaw responded to UFO report and encountered humanoid entity in reflective suit on highway. Photographed entity before it fled at incredible speed. Photos analyzed, found authentic.',
    description: `Police Chief Jeff Greenhaw responded to a report of a UFO landing. Upon arrival, he encountered a humanoid entity standing in the middle of the road.\n\nThe entity was approximately 6 feet tall, wearing what appeared to be a silvery reflective suit that Greenhaw described as looking like "rubbed aluminum foil." The entity had an antenna-like protrusion from its head.\n\nGreenhaw photographed the entity with his Polaroid camera, taking four photos. When he turned on his blue police lights, the entity turned and fled, running alongside the police car at speeds Greenhaw estimated at 35-40 mph.\n\nThe photographs were analyzed by multiple experts who found no evidence of fakery. The negatives showed a genuine photographed subject. Greenhaw's credibility as a law enforcement officer lent weight to the case, though he faced considerable ridicule.`,
    attributes: ['Police Witness', 'Photographic Evidence', 'Humanoid Entity', 'High-Speed Movement', 'Analyzed Photos'],
    reference: 'Falkville Metal Man',
    source: 'Falkville Police Department',
    witnessType: ['Civils', 'Haute qualité'],
    shape: ['Entité seule'],
    phenomena: ['Entité seule'],
  },
  {
    id: '26',
    date: '1967-10-04',
    time: '21:30',
    location: 'Shag Harbour, Nova Scotia',
    country: 'Canada',
    locationType: 'Côte',
    imageUrl: 'https://images.unsplash.com/photo-1601429661559-2d7d1e9b4ed2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxub3ZhJTIwc2NvdGlhJTIwY29hc3QlMjBoYXJib3J8ZW58MXx8fHwxNzY0NjgxMzI4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 12,
    strangeness: 9,
    summary: 'Multiple witnesses observe craft crash into harbor; official investigation.',
    duration: 30,
    elevation: 'Sea Level',
    coords: '43.5000° N, 65.7167° W',
    sourceId: 'CAN-1967-10-004',
    hatchDesc: 'Multiple witnesses including RCMP officers observed four lights crash into Shag Harbour. Official search and rescue operation launched. Object tracked underwater by military. Remains unexplained.',
    description: `At least 11 witnesses, including RCMP officers, observed four bright lights in formation descend at a 45-degree angle and crash into Shag Harbour.\n\nThe impact created a bright flash and a loud "whoosh." The object floated on the surface for a time, creating a thick yellow foam, before sinking approximately 300 yards from shore.\n\nRCMP and Coast Guard launched immediate search and rescue operations, assuming an aircraft had crashed. Divers found no aircraft wreckage. The Canadian military tracked an object underwater for several days.\n\nThe object allegedly traveled underwater to Government Point, where a second object joined it. Both objects remained stationary for days before departing. The incident was officially investigated and documented by the Royal Canadian Navy, RCMP, and Canadian Coast Guard. It remains in official files as unexplained.`,
    attributes: ['Water Landing', 'Multiple Witnesses', 'Official Investigation', 'Military Tracking', 'Underwater Object'],
    reference: 'Shag Harbour Incident',
    source: 'Royal Canadian Mounted Police / Canadian Navy',
    witnessType: ['Civils', 'Militaires', 'Haute qualité', 'Côtiers'],
    shape: ['Points lumineux'],
    phenomena: ['Submersible', 'Enquêtes gouvernementales'],
  },
  {
    id: '27',
    date: '1980-11-18',
    time: '06:00',
    location: 'Pecos, New Mexico',
    country: 'États-Unis',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1650397306410-32183656e4c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuZXclMjBtZXhpY28lMjByYW5jaCUyMGxhbmRzY2FwZXxlbnwxfHx8fDE3NjQ2ODEzMjl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 9,
    summary: 'Cash-Landrum case: witnesses suffer radiation-like illness after encounter.',
    duration: 20,
    elevation: '200 ft',
    coords: '29.6780° N, 95.1772° W',
    sourceId: 'CAS-1980-11-018',
    hatchDesc: 'Betty Cash, Vickie Landrum, and Colby Landrum encountered diamond-shaped object emitting flames. All suffered severe radiation-like injuries. Multiple helicopters observed escorting object. Medical documentation extensive.',
    description: `Betty Cash, Vickie Landrum, and Vickie's seven-year-old grandson Colby were driving when they encountered a large diamond-shaped object hovering over the road.\n\nThe object was emitting tremendous heat and flames from its bottom. It was so bright they had to shield their eyes. The car's metal exterior became too hot to touch. They estimated it was 100-130 feet above the road.\n\nAfter the object departed, they counted 23 CH-47 Chinook helicopters apparently escorting it. All three witnesses later developed symptoms consistent with radiation exposure: severe burns, hair loss, nausea, and vision problems.\n\nBetty Cash required hospitalization and suffered long-term health effects. Medical records documented radiation-like injuries. The witnesses sued the U.S. government, claiming the object was military. The case was dismissed as the government denied ownership, but medical evidence of injuries is well-documented.`,
    attributes: ['Physical Injuries', 'Medical Documentation', 'Multiple Witnesses', 'Military Helicopters', 'Radiation Effects'],
    reference: 'Cash-Landrum Incident',
    source: 'Medical Records / MUFON Investigation',
    witnessType: ['Civils'],
    shape: ['Delta'],
    phenomena: ['Effets sur humains', 'Effets sur bâtiments', 'Sons'],
  },
  {
    id: '28',
    date: '1954-11-02',
    time: '18:30',
    location: 'Quarouble, France',
    country: 'France',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1761052879074-be01002dc71f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVuY2glMjBydXJhbCUyMHJhaWxyb2FkJTIwdHJhY2tzfGVufDF8fHx8MTc2NDY4MTM1NXww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 9,
    summary: 'Railroad worker paralyzed by light from landed craft with entities.',
    duration: 15,
    elevation: 'Ground Level',
    coords: '50.3667° N, 3.6167° E',
    sourceId: 'FRA-1954-11-002',
    hatchDesc: 'Marius Dewilde encountered dark mass on railroad tracks. Two small entities in "diving suits" observed. Paralyzed by light from craft. Physical traces found on railroad ties. Part of 1954 French UFO wave.',
    description: `Railroad worker Marius Dewilde heard his dog barking and went outside his home near the railroad tracks. He observed a dark mass on the tracks approximately 6 yards long and 3 yards high.\n\nTwo small beings, less than 4 feet tall, were walking toward the object. They appeared to be wearing one-piece suits resembling diving suits with large helmets. Dewilde attempted to approach.\n\nA brilliant light from the craft paralyzed him completely. He could only watch as the beings entered the craft, which then rose vertically with a whistling sound, emitting thick steam, and disappeared.\n\nInvestigation by French Air Force found unusual indentations on the wooden railroad ties where the craft had rested. The wood showed signs of extreme pressure. Dewilde was considered a reliable witness. His case was part of the massive 1954 French UFO wave involving hundreds of sightings.`,
    attributes: ['Landing', 'Small Entities', 'Paralysis', 'Physical Traces', 'Official Investigation'],
    reference: 'French Air Force File',
    source: 'French Air Force / Gendarmerie',
    witnessType: ['Civils'],
    shape: ['Cigare'],
    phenomena: ['Atterrissage', 'Entité seule', 'Effets sur humains', 'Traces physiques (DRT)', 'Sons'],
  },
  {
    id: '29',
    date: '1973-11-06',
    time: '19:00',
    location: 'Fort Dix / McGuire AFB, New Jersey',
    country: 'États-Unis',
    locationType: 'Base militaire',
    imageUrl: 'https://images.unsplash.com/photo-1640894236254-589bd188cda7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaWxpdGFyeSUyMGJhc2UlMjBydW53YXklMjBuaWdodHxlbnwxfHx8fDE3NjQ2ODEzNTZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 11,
    strangeness: 10,
    summary: 'Military personnel shoot entity; craft lands on base runway.',
    duration: 45,
    elevation: 'Ground Level',
    coords: '40.0333° N, 74.5917° W',
    sourceId: 'MIL-1973-11-006',
    hatchDesc: 'Low-flying object over Fort Dix pursued by military police. Entity shot and killed after climbing base fence. Craft landed on McGuire AFB runway. Body and craft allegedly taken to Wright-Patterson AFB.',
    description: `A security patrol at Fort Dix observed a low-flying object over the base. As they pursued, they encountered a 4-foot tall grayish-brown entity with a large head climbing the perimeter fence.\n\nThe guard, feeling threatened, fired and allegedly killed the entity. The body fell on the New Jersey side of the fence. Almost simultaneously, a craft landed on the runway at neighboring McGuire Air Force Base.\n\nSecurity personnel from McGuire AFB rushed to Fort Dix to secure the entity's body while other teams secured the landed craft. Both the craft and the entity were allegedly loaded onto flatbed trucks.\n\nAccording to testimony from military personnel, both were transported to Wright-Patterson Air Force Base in Ohio. The incident was classified. Multiple military witnesses have come forward over the years, though official records remain classified or deny the event.`,
    attributes: ['Military Base', 'Entity Shot', 'Craft Landing', 'Multiple Military Witnesses', 'Alleged Recovery'],
    reference: 'Fort Dix Incident',
    source: 'Military Witnesses / Classified',
    witnessType: ['Militaires'],
    shape: ['Soucoupe'],
    phenomena: ['Atterrissage', 'Entité seule', 'Enquêtes gouvernementales'],
  },
  {
    id: '30',
    date: '1994-07-31',
    time: '03:00',
    location: 'Manassas, Virginia',
    country: 'États-Unis',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1709526494345-f8657247dd5d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aXJnaW5pYSUyMHN1YnVyYmFuJTIwbmlnaHR8ZW58MXx8fHwxNzY0NjgxMzU2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 9,
    strangeness: 8,
    summary: 'Witness films triangle hovering silently for 30 minutes.',
    duration: 30,
    elevation: '500 ft',
    coords: '38.7509° N, 77.4753° W',
    sourceId: 'VIR-1994-07-031',
    hatchDesc: 'Dennis Hawley video recorded large triangular craft hovering silently. Object size estimated at football field. Video analyzed, found authentic. Object departed at high speed.',
    description: `Dennis Hawley observed a large dark triangular object hovering silently approximately 500 feet above the ground. He grabbed his camcorder and filmed for approximately 30 minutes.\n\nThe object was massive - Hawley estimated it was the size of a football field. It had three white lights at the corners and one red light in the center. The object was completely silent and remained stationary.\n\nAfter hovering for an extended period, the object departed at incredible speed, accelerating in a way that would be impossible for conventional aircraft.\n\nThe video footage was analyzed by multiple experts. The footage was determined to be authentic and unmanipulated. The object's characteristics - massive size, silence, slow hovering, and rapid departure - matched numerous other triangle sighting reports from the 1990s.`,
    attributes: ['Video Evidence', 'Triangle', 'Silent', 'Extended Observation', 'Analyzed Footage'],
    reference: 'Manassas Triangle Video',
    source: 'Private Video / Expert Analysis',
    witnessType: ['Civils'],
    shape: ['Triangle', 'Delta'],
    phenomena: ['Faisceaux lumineux'],
  },
  {
    id: '31',
    date: '1978-12-31',
    time: '20:45',
    location: 'Kaikoura, New Zealand',
    country: 'Nouvelle-Zélande',
    locationType: 'Côte',
    imageUrl: 'https://images.unsplash.com/photo-1578406849741-e0ed9686fcbf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuZXclMjB6ZWFsYW5kJTIwY29hc3QlMjBtb3VudGFpbnN8ZW58MXx8fHwxNzY0NjgxMzU2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 12,
    strangeness: 9,
    summary: 'Film crew captures UFO on radar and film; air traffic control confirms.',
    duration: 120,
    elevation: 'Various',
    coords: '42.4004° S, 173.6751° E',
    sourceId: 'NZL-1978-12-031',
    hatchDesc: 'Australian television crew aboard Argosy aircraft filmed objects confirmed on air traffic control radar. Multiple objects, professional film footage, radar correlation. Wellington Air Traffic Control tracked objects.',
    description: `An Australian television crew was aboard an Argosy cargo aircraft specifically to investigate UFO reports when they encountered and filmed unidentified objects.\n\nWellington Air Traffic Control radar tracked unknown targets pacing the aircraft. The film crew, using professional equipment, captured footage of bright objects performing unusual maneuvers.\n\nThe objects appeared as extremely bright lights that would suddenly accelerate, decelerate, or change direction. Some appeared to follow the aircraft. Wellington ATC confirmed the radar returns correlated with the visual sightings.\n\nMultiple passes were made over two nights. The footage was analyzed extensively. The correlation between professional film footage, multiple trained observers, and radar confirmation makes this one of the most well-documented UFO cases. The New Zealand Defense Force investigated and could not explain the events.`,
    attributes: ['Film Evidence', 'Radar Confirmed', 'Air Traffic Control', 'Professional Crew', 'Official Investigation'],
    reference: 'Kaikoura Lights',
    source: 'New Zealand Defense Force / Channel 0 Network',
    witnessType: ['Civils', 'Haute qualité', 'Côtiers', 'Médias/Presse'],
    shape: ['Points lumineux'],
    phenomena: ['Enquêtes gouvernementales'],
  },
  {
    id: '32',
    date: '1965-07-01',
    time: '21:45',
    location: 'Valensole, France',
    country: 'France',
    locationType: 'Zone rurale',
    imageUrl: 'https://images.unsplash.com/photo-1723916687491-b294cf3653a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm92ZW5jZSUyMGxhdmVuZGVyJTIwZmllbGQlMjBmcmFuY2V8ZW58MXx8fHwxNzY0NjgxMzU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 11,
    strangeness: 9,
    summary: 'Farmer paralyzed by entities; lavender field shows landing traces.',
    duration: 15,
    elevation: 'Ground Level',
    coords: '43.8356° N, 5.9847° E',
    sourceId: 'FRA-1965-07-001',
    hatchDesc: 'Maurice Masse encountered egg-shaped craft and two child-sized entities in his lavender field. Paralyzed by device held by entity. Physical traces in field persisted for years. Investigated by police and GEIPAN.',
    description: `Farmer Maurice Masse heard a whistling sound and observed an egg-shaped object resting on legs in his lavender field. Two small beings, about 4 feet tall, were examining the lavender plants.\n\nThe beings had large heads, slanted eyes, and wore tight-fitting green suits. When Masse approached, one being pointed a tube-like device at him, completely paralyzing him.\n\nThe beings entered their craft, which departed vertically without sound. Masse remained paralyzed for approximately 20 minutes. When he could move, he examined the landing site.\n\nFour deep holes in a perfect geometric pattern marked where the craft had stood. The ground in the center was deeply compressed and desiccated. Nothing would grow in that exact spot for years. Police investigation confirmed the physical traces. Masse was considered an honest, reliable witness and never sought publicity.`,
    attributes: ['Landing', 'Humanoid Entities', 'Paralysis', 'Physical Traces', 'Long-term Ground Effects'],
    reference: 'Valensole Case',
    source: 'French Gendarmerie / GEIPAN',
    witnessType: ['Civils'],
    shape: ['Sphère'],
    phenomena: ['Atterrissage', 'Entité seule', 'Effets sur humains', 'Traces physiques (VEG)', 'Traces physiques (DRT)'],
  },
  {
    id: '33',
    date: '1976-03-15',
    time: '03:30',
    location: 'Anchorage, Alaska',
    country: 'États-Unis',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1638284380613-54701d00d50e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbmNob3JhZ2UlMjBhbGFza2ElMjBjaXR5JTIwbGlnaHRzfGVufDF8fHx8MTc2NDY4MTM1N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 10,
    strangeness: 8,
    summary: 'Cylindrical craft observed by multiple witnesses; power outage coincides.',
    duration: 45,
    elevation: '1,000 ft',
    coords: '61.2181° N, 149.9003° W',
    sourceId: 'ALA-1976-03-015',
    hatchDesc: 'Large cylindrical object with multiple windows observed by numerous Anchorage residents. Coincided with unexplained power outage affecting thousands. Object observed for 45 minutes.',
    description: `Dozens of Anchorage residents reported observing a large cylindrical craft with a row of illuminated windows hovering over the city.\n\nWitnesses described the object as approximately 300-400 feet long, dark metallic, with a row of bright rectangular windows along its side. The craft appeared to be rotating slowly.\n\nDuring the sighting, a widespread power outage affected large portions of Anchorage. The power company could find no explanation for the outage, and power was restored shortly after the object departed.\n\nMultiple independent witnesses from different locations reported the same object, providing consistent descriptions. The correlation between the UFO sighting and the unexplained power outage was noted by investigators but never officially explained.`,
    attributes: ['Mass Sighting', 'Cylindrical', 'Power Outage', 'Multiple Windows', 'Independent Witnesses'],
    reference: 'Anchorage Cylinder',
    source: 'Anchorage Daily News / MUFON',
    witnessType: ['Civils'],
    shape: ['Cylindre', 'Cigare'],
    phenomena: ['Effets sur bâtiments'],
  },
  {
    id: '34',
    date: '1957-09-19',
    time: '12:50',
    location: 'Ubatuba, Brazil',
    country: 'Brésil',
    locationType: 'Côte',
    imageUrl: 'https://images.unsplash.com/photo-1692312256111-24c55b48b76b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicmF6aWwlMjBiZWFjaCUyMGNvYXN0fGVufDF8fHx8MTc2NDY4MTM1N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 9,
    strangeness: 9,
    summary: 'Disc explodes over beach; witnesses recover metallic fragments.',
    duration: 5,
    elevation: '300 ft',
    coords: '23.4336° S, 45.0838° W',
    sourceId: 'BRA-1957-09-019',
    hatchDesc: 'Multiple witnesses observed disc-shaped object flying at high speed, banking sharply, then exploding. Metallic fragments recovered from beach. Laboratory analysis showed magnesium of unusual purity.',
    description: `Multiple witnesses on Ubatuba beach observed a disc-shaped object approaching at tremendous speed. The object was described as disk-like and glowing.\n\nThe object suddenly made an extremely sharp bank and began climbing at a steep angle. As it climbed, it appeared to explode, showering fragments into the sea and onto the beach.\n\nWitnesses recovered several metallic fragments from the beach. The pieces were lightweight and appeared to be of a metallic nature. Three fragments were sent to a newspaper which forwarded them for analysis.\n\nLaboratory analysis by multiple facilities, including Brazilian government labs and later by American scientists, revealed the metal was magnesium of extremely high purity - far exceeding commercial grade available at the time. The isotopic ratios were also unusual. The case remains unexplained with physical evidence still in existence.`,
    attributes: ['Physical Evidence', 'Multiple Witnesses', 'Explosion', 'Metal Analysis', 'Beach Recovery'],
    reference: 'Ubatuba Fragments',
    source: 'Brazilian laboratory reports / APRO',
    witnessType: ['Civils', 'Côtiers', 'Scientifiques'],
    shape: ['Soucoupe'],
    phenomena: ['Traces physiques (TRC)', 'Boule de feu'],
  },
  {
    id: '35',
    date: '1896-11-17',
    time: '18:00',
    location: 'Sacramento, California',
    country: 'États-Unis',
    locationType: 'Zone urbaine',
    imageUrl: 'https://images.unsplash.com/photo-1663436293556-3f0a1a1b9455?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWNyYW1lbnRvJTIwY2FsaWZvcm5pYSUyMHZpbnRhZ2UlMjBjaXR5fGVufDF8fHx8MTc2NDY4MTM1OHww&ixlib=rb-4.1.0&q=80&w=1080',
    credibility: 7,
    strangeness: 8,
    summary: 'Hundreds witness mysterious airship; beginning of 1896-97 wave.',
    duration: 30,
    elevation: '1,000 ft',
    coords: '38.5816° N, 121.4944° W',
    sourceId: 'HIS-1896-11-017',
    hatchDesc: 'First major sighting of Great Airship Mystery. Hundreds of Sacramento residents observed cigar-shaped craft with searchlight. Began wave of thousands of sightings across United States over 18 months.',
    description: `Hundreds of Sacramento residents observed a cigar-shaped object moving through the sky equipped with a brilliant searchlight sweeping the ground.\n\nWitnesses described the object as approximately 100 feet long with a cigar or dirigible shape. The searchlight was so bright it illuminated entire city blocks as it passed overhead.\n\nThe object moved against the wind at a steady pace, ruling out balloon explanations. It appeared to be under intelligent control. Witnesses included prominent citizens, making the sightings difficult to dismiss.\n\nThis sighting marked the beginning of the Great Airship Mystery of 1896-1897, during which thousands of people across the United States reported similar craft. The wave occurred before any known dirigible had been successfully flown, making the sightings particularly mysterious. Newspapers across the country documented hundreds of similar reports over the next 18 months.`,
    attributes: ['Historical', 'Mass Sighting', 'Searchlight', 'Cigar Shape', 'Beginning of Wave'],
    reference: 'Sacramento Bee 1896',
    source: 'Historical Newspaper Archives',
    witnessType: ['Civils'],
    shape: ['Cigare', 'Cylindre'],
    phenomena: ['Faisceaux lumineux'],
  },
];
